// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "monte_carlo_both_pri.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic monte_carlo_both_pri::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic monte_carlo_both_pri::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state1 = "1";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state2 = "10";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state3 = "100";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state4 = "1000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state5 = "10000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state6 = "100000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state7 = "1000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state8 = "10000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state9 = "100000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state10 = "1000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state11 = "10000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state12 = "100000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state45 = "100000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state46 = "1000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state47 = "10000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state48 = "100000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state49 = "1000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state50 = "10000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state51 = "100000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state52 = "1000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state53 = "10000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state54 = "100000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state55 = "1000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state56 = "10000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state57 = "100000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state58 = "1000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state59 = "10000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state60 = "100000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state61 = "1000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state62 = "10000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state63 = "100000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state64 = "1000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state65 = "10000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state66 = "100000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state67 = "1000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state68 = "10000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state69 = "100000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state70 = "1000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state71 = "10000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state72 = "100000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state73 = "1000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state74 = "10000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state75 = "100000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state76 = "1000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state77 = "10000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state78 = "100000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state79 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state80 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state81 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state82 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state83 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state84 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state85 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state86 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state87 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state88 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state89 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state90 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state91 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state92 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state93 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state94 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state95 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state96 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state97 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state98 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state99 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state100 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state101 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state102 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state103 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state104 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state105 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state106 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state107 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state108 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state109 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state110 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state111 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<112> monte_carlo_both_pri::ap_ST_fsm_state112 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_7 = "111";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_2E = "101110";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_44 = "1000100";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_29 = "101001";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_69 = "1101001";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_39 = "111001";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_3F = "111111";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_1 = "1";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_2 = "10";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_9 = "1001";
const sc_lv<1> monte_carlo_both_pri::ap_const_lv1_1 = "1";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_A = "1010";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_34 = "110100";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_3A = "111010";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_46 = "1000110";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_4B = "1001011";
const sc_lv<64> monte_carlo_both_pri::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<24> monte_carlo_both_pri::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<64> monte_carlo_both_pri::ap_const_lv64_3FA47AE147AE147C = "11111110100100011110101110000101000111101011100001010001111100";
const sc_lv<64> monte_carlo_both_pri::ap_const_lv64_3FE0A3D70A3D70A4 = "11111111100000101000111101011100001010001111010111000010100100";
const sc_lv<1> monte_carlo_both_pri::ap_const_lv1_0 = "0";
const sc_lv<64> monte_carlo_both_pri::ap_const_lv64_C059000000000000 = "1100000001011001000000000000000000000000000000000000000000000000";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_3 = "11";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_2A = "101010";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_40 = "1000000";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_47 = "1000111";
const sc_lv<64> monte_carlo_both_pri::ap_const_lv64_4059000000000000 = "100000001011001000000000000000000000000000000000000000000000000";
const sc_lv<64> monte_carlo_both_pri::ap_const_lv64_3FE0000000000000 = "11111111100000000000000000000000000000000000000000000000000000";
const sc_lv<64> monte_carlo_both_pri::ap_const_lv64_4059C2E8B55BA1C6 = "100000001011001110000101110100010110101010110111010000111000110";
const sc_lv<64> monte_carlo_both_pri::ap_const_lv64_3FEE7078B0A726A6 = "11111111101110011100000111100010110000101001110010011010100110";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_B = "1011";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_2F = "101111";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_6A = "1101010";
const sc_lv<64> monte_carlo_both_pri::ap_const_lv64_416312D000000000 = "100000101100011000100101101000000000000000000000000000000000000";
const sc_lv<64> monte_carlo_both_pri::ap_const_lv64_3F1A36E2EB1C432D = "11111100011010001101101110001011101011000111000100001100101101";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_8 = "1000";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_45 = "1000101";
const sc_lv<24> monte_carlo_both_pri::ap_const_lv24_989680 = "100110001001011010000000";
const sc_lv<24> monte_carlo_both_pri::ap_const_lv24_1 = "1";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_3E = "111110";
const sc_lv<11> monte_carlo_both_pri::ap_const_lv11_7FF = "11111111111";
const sc_lv<52> monte_carlo_both_pri::ap_const_lv52_0 = "0000000000000000000000000000000000000000000000000000";
const sc_lv<64> monte_carlo_both_pri::ap_const_lv64_8000000000000000 = "1000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_6F = "1101111";
const sc_lv<2> monte_carlo_both_pri::ap_const_lv2_0 = "00";
const sc_lv<2> monte_carlo_both_pri::ap_const_lv2_1 = "1";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_35 = "110101";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_36 = "110110";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_37 = "110111";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_38 = "111000";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_30 = "110000";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_31 = "110001";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_32 = "110010";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_33 = "110011";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_3B = "111011";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_3C = "111100";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_3D = "111101";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_6B = "1101011";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_6C = "1101100";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_6D = "1101101";
const sc_lv<32> monte_carlo_both_pri::ap_const_lv32_6E = "1101110";
const sc_lv<5> monte_carlo_both_pri::ap_const_lv5_4 = "100";
const sc_lv<5> monte_carlo_both_pri::ap_const_lv5_3 = "11";
const sc_lv<5> monte_carlo_both_pri::ap_const_lv5_2 = "10";
const bool monte_carlo_both_pri::ap_const_boolean_1 = true;

monte_carlo_both_pri::monte_carlo_both_pri(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_gaussian_box_muller_fu_126 = new gaussian_box_muller("grp_gaussian_box_muller_fu_126");
    grp_gaussian_box_muller_fu_126->ap_clk(ap_clk);
    grp_gaussian_box_muller_fu_126->ap_rst(ap_rst);
    grp_gaussian_box_muller_fu_126->ap_start(grp_gaussian_box_muller_fu_126_ap_start);
    grp_gaussian_box_muller_fu_126->ap_done(grp_gaussian_box_muller_fu_126_ap_done);
    grp_gaussian_box_muller_fu_126->ap_idle(grp_gaussian_box_muller_fu_126_ap_idle);
    grp_gaussian_box_muller_fu_126->ap_ready(grp_gaussian_box_muller_fu_126_ap_ready);
    grp_gaussian_box_muller_fu_126->ap_return(grp_gaussian_box_muller_fu_126_ap_return);
    grp_custom_exp_double_s_fu_132 = new custom_exp_double_s("grp_custom_exp_double_s_fu_132");
    grp_custom_exp_double_s_fu_132->ap_clk(ap_clk);
    grp_custom_exp_double_s_fu_132->ap_rst(ap_rst);
    grp_custom_exp_double_s_fu_132->ap_start(grp_custom_exp_double_s_fu_132_ap_start);
    grp_custom_exp_double_s_fu_132->ap_done(grp_custom_exp_double_s_fu_132_ap_done);
    grp_custom_exp_double_s_fu_132->ap_idle(grp_custom_exp_double_s_fu_132_ap_idle);
    grp_custom_exp_double_s_fu_132->ap_ready(grp_custom_exp_double_s_fu_132_ap_ready);
    grp_custom_exp_double_s_fu_132->x(reg_206);
    grp_custom_exp_double_s_fu_132->ap_return(grp_custom_exp_double_s_fu_132_ap_return);
    dut_dadddsub_64nsbkb_U22 = new dut_dadddsub_64nsbkb<1,5,64,64,64>("dut_dadddsub_64nsbkb_U22");
    dut_dadddsub_64nsbkb_U22->clk(ap_clk);
    dut_dadddsub_64nsbkb_U22->reset(ap_rst);
    dut_dadddsub_64nsbkb_U22->din0(grp_fu_137_p0);
    dut_dadddsub_64nsbkb_U22->din1(grp_fu_137_p1);
    dut_dadddsub_64nsbkb_U22->opcode(grp_fu_137_opcode);
    dut_dadddsub_64nsbkb_U22->ce(ap_var_for_const0);
    dut_dadddsub_64nsbkb_U22->dout(grp_fu_137_p2);
    dut_dadddsub_64nsbkb_U23 = new dut_dadddsub_64nsbkb<1,5,64,64,64>("dut_dadddsub_64nsbkb_U23");
    dut_dadddsub_64nsbkb_U23->clk(ap_clk);
    dut_dadddsub_64nsbkb_U23->reset(ap_rst);
    dut_dadddsub_64nsbkb_U23->din0(grp_fu_145_p0);
    dut_dadddsub_64nsbkb_U23->din1(grp_fu_145_p1);
    dut_dadddsub_64nsbkb_U23->opcode(grp_fu_145_opcode);
    dut_dadddsub_64nsbkb_U23->ce(ap_var_for_const0);
    dut_dadddsub_64nsbkb_U23->dout(grp_fu_145_p2);
    dut_dmul_64ns_64ndEe_U24 = new dut_dmul_64ns_64ndEe<1,6,64,64,64>("dut_dmul_64ns_64ndEe_U24");
    dut_dmul_64ns_64ndEe_U24->clk(ap_clk);
    dut_dmul_64ns_64ndEe_U24->reset(ap_rst);
    dut_dmul_64ns_64ndEe_U24->din0(grp_fu_152_p0);
    dut_dmul_64ns_64ndEe_U24->din1(grp_fu_152_p1);
    dut_dmul_64ns_64ndEe_U24->ce(grp_fu_152_ce);
    dut_dmul_64ns_64ndEe_U24->dout(grp_fu_152_p2);
    dut_dmul_64ns_64ndEe_U25 = new dut_dmul_64ns_64ndEe<1,6,64,64,64>("dut_dmul_64ns_64ndEe_U25");
    dut_dmul_64ns_64ndEe_U25->clk(ap_clk);
    dut_dmul_64ns_64ndEe_U25->reset(ap_rst);
    dut_dmul_64ns_64ndEe_U25->din0(tmp_1_reg_498);
    dut_dmul_64ns_64ndEe_U25->din1(ap_var_for_const1);
    dut_dmul_64ns_64ndEe_U25->ce(ap_var_for_const0);
    dut_dmul_64ns_64ndEe_U25->dout(grp_fu_162_p2);
    dut_ddiv_64ns_64neOg_U26 = new dut_ddiv_64ns_64neOg<1,31,64,64,64>("dut_ddiv_64ns_64neOg_U26");
    dut_ddiv_64ns_64neOg_U26->clk(ap_clk);
    dut_ddiv_64ns_64neOg_U26->reset(ap_rst);
    dut_ddiv_64ns_64neOg_U26->din0(grp_fu_167_p0);
    dut_ddiv_64ns_64neOg_U26->din1(grp_fu_167_p1);
    dut_ddiv_64ns_64neOg_U26->ce(ap_var_for_const0);
    dut_ddiv_64ns_64neOg_U26->dout(grp_fu_167_p2);
    dut_ddiv_64ns_64neOg_U27 = new dut_ddiv_64ns_64neOg<1,31,64,64,64>("dut_ddiv_64ns_64neOg_U27");
    dut_ddiv_64ns_64neOg_U27->clk(ap_clk);
    dut_ddiv_64ns_64neOg_U27->reset(ap_rst);
    dut_ddiv_64ns_64neOg_U27->din0(put_payoff_sum_0_reg_68);
    dut_ddiv_64ns_64neOg_U27->din1(ap_var_for_const2);
    dut_ddiv_64ns_64neOg_U27->ce(ap_var_for_const0);
    dut_ddiv_64ns_64neOg_U27->dout(grp_fu_173_p2);
    dut_dcmp_64ns_64nfYi_U28 = new dut_dcmp_64ns_64nfYi<1,2,64,64,1>("dut_dcmp_64ns_64nfYi_U28");
    dut_dcmp_64ns_64nfYi_U28->clk(ap_clk);
    dut_dcmp_64ns_64nfYi_U28->reset(ap_rst);
    dut_dcmp_64ns_64nfYi_U28->din0(grp_fu_181_p0);
    dut_dcmp_64ns_64nfYi_U28->din1(grp_fu_181_p1);
    dut_dcmp_64ns_64nfYi_U28->ce(ap_var_for_const0);
    dut_dcmp_64ns_64nfYi_U28->opcode(grp_fu_181_opcode);
    dut_dcmp_64ns_64nfYi_U28->dout(grp_fu_181_p2);
    dut_dcmp_64ns_64nfYi_U29 = new dut_dcmp_64ns_64nfYi<1,2,64,64,1>("dut_dcmp_64ns_64nfYi_U29");
    dut_dcmp_64ns_64nfYi_U29->clk(ap_clk);
    dut_dcmp_64ns_64nfYi_U29->reset(ap_rst);
    dut_dcmp_64ns_64nfYi_U29->din0(a_assign_1_reg_471);
    dut_dcmp_64ns_64nfYi_U29->din1(ap_var_for_const3);
    dut_dcmp_64ns_64nfYi_U29->ce(ap_var_for_const0);
    dut_dcmp_64ns_64nfYi_U29->opcode(ap_var_for_const4);
    dut_dcmp_64ns_64nfYi_U29->dout(grp_fu_188_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_and_ln50_1_fu_402_p2);
    sensitive << ( or_ln50_1_fu_396_p2 );
    sensitive << ( grp_fu_188_p2 );

    SC_METHOD(thread_and_ln50_fu_353_p2);
    sensitive << ( grp_fu_181_p2 );
    sensitive << ( or_ln50_fu_347_p2 );

    SC_METHOD(thread_and_ln54_fu_261_p2);
    sensitive << ( or_ln54_fu_255_p2 );
    sensitive << ( grp_fu_181_p2 );

    SC_METHOD(thread_and_ln83_fu_311_p2);
    sensitive << ( grp_fu_181_p2 );
    sensitive << ( or_ln83_fu_307_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state106);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state107);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state108);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state109);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state110);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state111);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state112);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state42);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state43);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state47);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state48);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state49);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state50);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state51);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state52);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state53);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state54);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state55);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state56);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state57);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state58);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state59);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state60);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state61);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state62);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state63);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state64);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state65);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state69);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state70);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state71);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state72);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state76);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state112 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state112 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( grp_fu_152_p2 );
    sensitive << ( ap_CS_fsm_state112 );
    sensitive << ( ap_return_0_preg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_CS_fsm_state112 );
    sensitive << ( grp_fu_162_p2 );
    sensitive << ( ap_return_1_preg );

    SC_METHOD(thread_bitcast_ln50_1_fu_367_p1);
    sensitive << ( a_assign_1_reg_471 );

    SC_METHOD(thread_bitcast_ln50_fu_317_p1);
    sensitive << ( reg_193 );

    SC_METHOD(thread_bitcast_ln54_1_fu_273_p1);
    sensitive << ( xor_ln54_fu_267_p2 );

    SC_METHOD(thread_bitcast_ln54_fu_225_p1);
    sensitive << ( reg_193 );

    SC_METHOD(thread_bitcast_ln83_fu_277_p1);
    sensitive << ( phi_ln54_reg_116 );

    SC_METHOD(thread_grp_custom_exp_double_s_fu_132_ap_start);
    sensitive << ( grp_custom_exp_double_s_fu_132_ap_start_reg );

    SC_METHOD(thread_grp_fu_137_opcode);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state65 );
    sensitive << ( ap_CS_fsm_state72 );

    SC_METHOD(thread_grp_fu_137_p0);
    sensitive << ( reg_206 );
    sensitive << ( call_payoff_sum_0_reg_56 );
    sensitive << ( guess_0_i_reg_91 );
    sensitive << ( nextGuess_reg_103 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state65 );
    sensitive << ( ap_CS_fsm_state72 );

    SC_METHOD(thread_grp_fu_137_p1);
    sensitive << ( reg_200 );
    sensitive << ( select_ln50_reg_478 );
    sensitive << ( nextGuess_reg_103 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state65 );
    sensitive << ( ap_CS_fsm_state72 );

    SC_METHOD(thread_grp_fu_145_opcode);
    sensitive << ( ap_CS_fsm_state65 );
    sensitive << ( ap_CS_fsm_state72 );

    SC_METHOD(thread_grp_fu_145_p0);
    sensitive << ( put_payoff_sum_0_reg_68 );
    sensitive << ( ap_CS_fsm_state65 );
    sensitive << ( ap_CS_fsm_state72 );

    SC_METHOD(thread_grp_fu_145_p1);
    sensitive << ( reg_206 );
    sensitive << ( select_ln50_1_reg_483 );
    sensitive << ( ap_CS_fsm_state65 );
    sensitive << ( ap_CS_fsm_state72 );

    SC_METHOD(thread_grp_fu_152_ce);
    sensitive << ( ap_CS_fsm_state58 );
    sensitive << ( ap_CS_fsm_state64 );
    sensitive << ( ap_CS_fsm_state53 );
    sensitive << ( ap_CS_fsm_state59 );
    sensitive << ( grp_custom_exp_double_s_fu_132_ap_done );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state48 );
    sensitive << ( ap_CS_fsm_state107 );
    sensitive << ( ap_CS_fsm_state112 );
    sensitive << ( ap_CS_fsm_state54 );
    sensitive << ( ap_CS_fsm_state55 );
    sensitive << ( ap_CS_fsm_state56 );
    sensitive << ( ap_CS_fsm_state57 );
    sensitive << ( ap_CS_fsm_state49 );
    sensitive << ( ap_CS_fsm_state50 );
    sensitive << ( ap_CS_fsm_state51 );
    sensitive << ( ap_CS_fsm_state52 );
    sensitive << ( ap_CS_fsm_state60 );
    sensitive << ( ap_CS_fsm_state61 );
    sensitive << ( ap_CS_fsm_state62 );
    sensitive << ( ap_CS_fsm_state63 );
    sensitive << ( ap_CS_fsm_state108 );
    sensitive << ( ap_CS_fsm_state109 );
    sensitive << ( ap_CS_fsm_state110 );
    sensitive << ( ap_CS_fsm_state111 );

    SC_METHOD(thread_grp_fu_152_p0);
    sensitive << ( reg_193 );
    sensitive << ( reg_200 );
    sensitive << ( grp_custom_exp_double_s_fu_132_ap_return );
    sensitive << ( ap_CS_fsm_state59 );
    sensitive << ( nextGuess_reg_103 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state48 );
    sensitive << ( ap_CS_fsm_state107 );

    SC_METHOD(thread_grp_fu_152_p1);
    sensitive << ( gauss_bm_reg_435 );
    sensitive << ( ap_CS_fsm_state59 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state48 );
    sensitive << ( ap_CS_fsm_state107 );

    SC_METHOD(thread_grp_fu_167_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( call_payoff_sum_0_reg_56 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_grp_fu_167_p1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( nextGuess_reg_103 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_grp_fu_181_opcode);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state70 );

    SC_METHOD(thread_grp_fu_181_p0);
    sensitive << ( reg_193 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( phi_ln54_reg_116 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state70 );

    SC_METHOD(thread_grp_fu_181_p1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state70 );

    SC_METHOD(thread_grp_gaussian_box_muller_fu_126_ap_start);
    sensitive << ( grp_gaussian_box_muller_fu_126_ap_start_reg );

    SC_METHOD(thread_i_fu_219_p2);
    sensitive << ( i_0_reg_80 );

    SC_METHOD(thread_icmp_ln184_fu_213_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_80 );

    SC_METHOD(thread_icmp_ln50_1_fu_341_p2);
    sensitive << ( ap_CS_fsm_state71 );
    sensitive << ( trunc_ln50_fu_331_p1 );

    SC_METHOD(thread_icmp_ln50_2_fu_384_p2);
    sensitive << ( ap_CS_fsm_state71 );
    sensitive << ( tmp_6_fu_370_p4 );

    SC_METHOD(thread_icmp_ln50_3_fu_390_p2);
    sensitive << ( ap_CS_fsm_state71 );
    sensitive << ( trunc_ln50_1_fu_380_p1 );

    SC_METHOD(thread_icmp_ln50_fu_335_p2);
    sensitive << ( ap_CS_fsm_state71 );
    sensitive << ( tmp_s_fu_321_p4 );

    SC_METHOD(thread_icmp_ln54_1_fu_249_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( trunc_ln54_fu_239_p1 );

    SC_METHOD(thread_icmp_ln54_fu_243_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_fu_229_p4 );

    SC_METHOD(thread_icmp_ln83_1_fu_301_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( trunc_ln83_fu_291_p1 );

    SC_METHOD(thread_icmp_ln83_fu_295_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( tmp_3_fu_281_p4 );

    SC_METHOD(thread_or_ln50_1_fu_396_p2);
    sensitive << ( icmp_ln50_3_fu_390_p2 );
    sensitive << ( icmp_ln50_2_fu_384_p2 );

    SC_METHOD(thread_or_ln50_fu_347_p2);
    sensitive << ( icmp_ln50_1_fu_341_p2 );
    sensitive << ( icmp_ln50_fu_335_p2 );

    SC_METHOD(thread_or_ln54_fu_255_p2);
    sensitive << ( icmp_ln54_1_fu_249_p2 );
    sensitive << ( icmp_ln54_fu_243_p2 );

    SC_METHOD(thread_or_ln83_fu_307_p2);
    sensitive << ( icmp_ln83_reg_448 );
    sensitive << ( icmp_ln83_1_reg_453 );

    SC_METHOD(thread_select_ln50_1_fu_408_p3);
    sensitive << ( a_assign_1_reg_471 );
    sensitive << ( and_ln50_1_fu_402_p2 );

    SC_METHOD(thread_select_ln50_fu_359_p3);
    sensitive << ( reg_193 );
    sensitive << ( and_ln50_fu_353_p2 );

    SC_METHOD(thread_tmp_3_fu_281_p4);
    sensitive << ( bitcast_ln83_fu_277_p1 );

    SC_METHOD(thread_tmp_6_fu_370_p4);
    sensitive << ( bitcast_ln50_1_fu_367_p1 );

    SC_METHOD(thread_tmp_fu_229_p4);
    sensitive << ( bitcast_ln54_fu_225_p1 );

    SC_METHOD(thread_tmp_s_fu_321_p4);
    sensitive << ( bitcast_ln50_fu_317_p1 );

    SC_METHOD(thread_trunc_ln50_1_fu_380_p1);
    sensitive << ( bitcast_ln50_1_fu_367_p1 );

    SC_METHOD(thread_trunc_ln50_fu_331_p1);
    sensitive << ( bitcast_ln50_fu_317_p1 );

    SC_METHOD(thread_trunc_ln54_fu_239_p1);
    sensitive << ( bitcast_ln54_fu_225_p1 );

    SC_METHOD(thread_trunc_ln83_fu_291_p1);
    sensitive << ( bitcast_ln83_fu_277_p1 );

    SC_METHOD(thread_xor_ln54_fu_267_p2);
    sensitive << ( bitcast_ln54_fu_225_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_gaussian_box_muller_fu_126_ap_done );
    sensitive << ( ap_CS_fsm_state59 );
    sensitive << ( grp_custom_exp_double_s_fu_132_ap_done );
    sensitive << ( icmp_ln184_fu_213_p2 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( and_ln83_fu_311_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const3);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const4);

    ap_CS_fsm = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    grp_gaussian_box_muller_fu_126_ap_start_reg = SC_LOGIC_0;
    grp_custom_exp_double_s_fu_132_ap_start_reg = SC_LOGIC_0;
    ap_return_0_preg = "0000000000000000000000000000000000000000000000000000000000000000";
    ap_return_1_preg = "0000000000000000000000000000000000000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "monte_carlo_both_pri_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_137_p2, "grp_fu_137_p2");
    sc_trace(mVcdFile, reg_193, "reg_193");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state47, "ap_CS_fsm_state47");
    sc_trace(mVcdFile, ap_CS_fsm_state69, "ap_CS_fsm_state69");
    sc_trace(mVcdFile, grp_fu_167_p2, "grp_fu_167_p2");
    sc_trace(mVcdFile, reg_200, "reg_200");
    sc_trace(mVcdFile, ap_CS_fsm_state42, "ap_CS_fsm_state42");
    sc_trace(mVcdFile, ap_CS_fsm_state106, "ap_CS_fsm_state106");
    sc_trace(mVcdFile, grp_fu_152_p2, "grp_fu_152_p2");
    sc_trace(mVcdFile, reg_206, "reg_206");
    sc_trace(mVcdFile, ap_CS_fsm_state58, "ap_CS_fsm_state58");
    sc_trace(mVcdFile, ap_CS_fsm_state64, "ap_CS_fsm_state64");
    sc_trace(mVcdFile, i_fu_219_p2, "i_fu_219_p2");
    sc_trace(mVcdFile, i_reg_430, "i_reg_430");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, grp_gaussian_box_muller_fu_126_ap_return, "grp_gaussian_box_muller_fu_126_ap_return");
    sc_trace(mVcdFile, gauss_bm_reg_435, "gauss_bm_reg_435");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, grp_gaussian_box_muller_fu_126_ap_ready, "grp_gaussian_box_muller_fu_126_ap_ready");
    sc_trace(mVcdFile, grp_gaussian_box_muller_fu_126_ap_done, "grp_gaussian_box_muller_fu_126_ap_done");
    sc_trace(mVcdFile, bitcast_ln54_1_fu_273_p1, "bitcast_ln54_1_fu_273_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, and_ln54_fu_261_p2, "and_ln54_fu_261_p2");
    sc_trace(mVcdFile, icmp_ln83_fu_295_p2, "icmp_ln83_fu_295_p2");
    sc_trace(mVcdFile, icmp_ln83_reg_448, "icmp_ln83_reg_448");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, icmp_ln83_1_fu_301_p2, "icmp_ln83_1_fu_301_p2");
    sc_trace(mVcdFile, icmp_ln83_1_reg_453, "icmp_ln83_1_reg_453");
    sc_trace(mVcdFile, ap_CS_fsm_state53, "ap_CS_fsm_state53");
    sc_trace(mVcdFile, grp_custom_exp_double_s_fu_132_ap_return, "grp_custom_exp_double_s_fu_132_ap_return");
    sc_trace(mVcdFile, ap_CS_fsm_state59, "ap_CS_fsm_state59");
    sc_trace(mVcdFile, grp_custom_exp_double_s_fu_132_ap_ready, "grp_custom_exp_double_s_fu_132_ap_ready");
    sc_trace(mVcdFile, grp_custom_exp_double_s_fu_132_ap_done, "grp_custom_exp_double_s_fu_132_ap_done");
    sc_trace(mVcdFile, grp_fu_145_p2, "grp_fu_145_p2");
    sc_trace(mVcdFile, a_assign_1_reg_471, "a_assign_1_reg_471");
    sc_trace(mVcdFile, select_ln50_fu_359_p3, "select_ln50_fu_359_p3");
    sc_trace(mVcdFile, select_ln50_reg_478, "select_ln50_reg_478");
    sc_trace(mVcdFile, ap_CS_fsm_state71, "ap_CS_fsm_state71");
    sc_trace(mVcdFile, select_ln50_1_fu_408_p3, "select_ln50_1_fu_408_p3");
    sc_trace(mVcdFile, select_ln50_1_reg_483, "select_ln50_1_reg_483");
    sc_trace(mVcdFile, ap_CS_fsm_state76, "ap_CS_fsm_state76");
    sc_trace(mVcdFile, grp_fu_173_p2, "grp_fu_173_p2");
    sc_trace(mVcdFile, tmp_1_reg_498, "tmp_1_reg_498");
    sc_trace(mVcdFile, grp_gaussian_box_muller_fu_126_ap_start, "grp_gaussian_box_muller_fu_126_ap_start");
    sc_trace(mVcdFile, grp_gaussian_box_muller_fu_126_ap_idle, "grp_gaussian_box_muller_fu_126_ap_idle");
    sc_trace(mVcdFile, grp_custom_exp_double_s_fu_132_ap_start, "grp_custom_exp_double_s_fu_132_ap_start");
    sc_trace(mVcdFile, grp_custom_exp_double_s_fu_132_ap_idle, "grp_custom_exp_double_s_fu_132_ap_idle");
    sc_trace(mVcdFile, call_payoff_sum_0_reg_56, "call_payoff_sum_0_reg_56");
    sc_trace(mVcdFile, put_payoff_sum_0_reg_68, "put_payoff_sum_0_reg_68");
    sc_trace(mVcdFile, i_0_reg_80, "i_0_reg_80");
    sc_trace(mVcdFile, guess_0_i_reg_91, "guess_0_i_reg_91");
    sc_trace(mVcdFile, nextGuess_reg_103, "nextGuess_reg_103");
    sc_trace(mVcdFile, phi_ln54_reg_116, "phi_ln54_reg_116");
    sc_trace(mVcdFile, grp_gaussian_box_muller_fu_126_ap_start_reg, "grp_gaussian_box_muller_fu_126_ap_start_reg");
    sc_trace(mVcdFile, icmp_ln184_fu_213_p2, "icmp_ln184_fu_213_p2");
    sc_trace(mVcdFile, grp_custom_exp_double_s_fu_132_ap_start_reg, "grp_custom_exp_double_s_fu_132_ap_start_reg");
    sc_trace(mVcdFile, grp_fu_137_p0, "grp_fu_137_p0");
    sc_trace(mVcdFile, grp_fu_137_p1, "grp_fu_137_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state43, "ap_CS_fsm_state43");
    sc_trace(mVcdFile, ap_CS_fsm_state65, "ap_CS_fsm_state65");
    sc_trace(mVcdFile, ap_CS_fsm_state72, "ap_CS_fsm_state72");
    sc_trace(mVcdFile, grp_fu_145_p0, "grp_fu_145_p0");
    sc_trace(mVcdFile, grp_fu_145_p1, "grp_fu_145_p1");
    sc_trace(mVcdFile, grp_fu_152_p0, "grp_fu_152_p0");
    sc_trace(mVcdFile, grp_fu_152_p1, "grp_fu_152_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state48, "ap_CS_fsm_state48");
    sc_trace(mVcdFile, ap_CS_fsm_state107, "ap_CS_fsm_state107");
    sc_trace(mVcdFile, grp_fu_167_p0, "grp_fu_167_p0");
    sc_trace(mVcdFile, grp_fu_167_p1, "grp_fu_167_p1");
    sc_trace(mVcdFile, grp_fu_181_p0, "grp_fu_181_p0");
    sc_trace(mVcdFile, grp_fu_181_p1, "grp_fu_181_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state70, "ap_CS_fsm_state70");
    sc_trace(mVcdFile, bitcast_ln54_fu_225_p1, "bitcast_ln54_fu_225_p1");
    sc_trace(mVcdFile, tmp_fu_229_p4, "tmp_fu_229_p4");
    sc_trace(mVcdFile, trunc_ln54_fu_239_p1, "trunc_ln54_fu_239_p1");
    sc_trace(mVcdFile, icmp_ln54_1_fu_249_p2, "icmp_ln54_1_fu_249_p2");
    sc_trace(mVcdFile, icmp_ln54_fu_243_p2, "icmp_ln54_fu_243_p2");
    sc_trace(mVcdFile, or_ln54_fu_255_p2, "or_ln54_fu_255_p2");
    sc_trace(mVcdFile, grp_fu_181_p2, "grp_fu_181_p2");
    sc_trace(mVcdFile, xor_ln54_fu_267_p2, "xor_ln54_fu_267_p2");
    sc_trace(mVcdFile, bitcast_ln83_fu_277_p1, "bitcast_ln83_fu_277_p1");
    sc_trace(mVcdFile, tmp_3_fu_281_p4, "tmp_3_fu_281_p4");
    sc_trace(mVcdFile, trunc_ln83_fu_291_p1, "trunc_ln83_fu_291_p1");
    sc_trace(mVcdFile, or_ln83_fu_307_p2, "or_ln83_fu_307_p2");
    sc_trace(mVcdFile, bitcast_ln50_fu_317_p1, "bitcast_ln50_fu_317_p1");
    sc_trace(mVcdFile, tmp_s_fu_321_p4, "tmp_s_fu_321_p4");
    sc_trace(mVcdFile, trunc_ln50_fu_331_p1, "trunc_ln50_fu_331_p1");
    sc_trace(mVcdFile, icmp_ln50_1_fu_341_p2, "icmp_ln50_1_fu_341_p2");
    sc_trace(mVcdFile, icmp_ln50_fu_335_p2, "icmp_ln50_fu_335_p2");
    sc_trace(mVcdFile, or_ln50_fu_347_p2, "or_ln50_fu_347_p2");
    sc_trace(mVcdFile, and_ln50_fu_353_p2, "and_ln50_fu_353_p2");
    sc_trace(mVcdFile, bitcast_ln50_1_fu_367_p1, "bitcast_ln50_1_fu_367_p1");
    sc_trace(mVcdFile, tmp_6_fu_370_p4, "tmp_6_fu_370_p4");
    sc_trace(mVcdFile, trunc_ln50_1_fu_380_p1, "trunc_ln50_1_fu_380_p1");
    sc_trace(mVcdFile, icmp_ln50_3_fu_390_p2, "icmp_ln50_3_fu_390_p2");
    sc_trace(mVcdFile, icmp_ln50_2_fu_384_p2, "icmp_ln50_2_fu_384_p2");
    sc_trace(mVcdFile, or_ln50_1_fu_396_p2, "or_ln50_1_fu_396_p2");
    sc_trace(mVcdFile, grp_fu_188_p2, "grp_fu_188_p2");
    sc_trace(mVcdFile, and_ln50_1_fu_402_p2, "and_ln50_1_fu_402_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state112, "ap_CS_fsm_state112");
    sc_trace(mVcdFile, grp_fu_162_p2, "grp_fu_162_p2");
    sc_trace(mVcdFile, grp_fu_137_opcode, "grp_fu_137_opcode");
    sc_trace(mVcdFile, grp_fu_145_opcode, "grp_fu_145_opcode");
    sc_trace(mVcdFile, grp_fu_152_ce, "grp_fu_152_ce");
    sc_trace(mVcdFile, and_ln83_fu_311_p2, "and_ln83_fu_311_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state54, "ap_CS_fsm_state54");
    sc_trace(mVcdFile, ap_CS_fsm_state55, "ap_CS_fsm_state55");
    sc_trace(mVcdFile, ap_CS_fsm_state56, "ap_CS_fsm_state56");
    sc_trace(mVcdFile, ap_CS_fsm_state57, "ap_CS_fsm_state57");
    sc_trace(mVcdFile, ap_CS_fsm_state49, "ap_CS_fsm_state49");
    sc_trace(mVcdFile, ap_CS_fsm_state50, "ap_CS_fsm_state50");
    sc_trace(mVcdFile, ap_CS_fsm_state51, "ap_CS_fsm_state51");
    sc_trace(mVcdFile, ap_CS_fsm_state52, "ap_CS_fsm_state52");
    sc_trace(mVcdFile, ap_CS_fsm_state60, "ap_CS_fsm_state60");
    sc_trace(mVcdFile, ap_CS_fsm_state61, "ap_CS_fsm_state61");
    sc_trace(mVcdFile, ap_CS_fsm_state62, "ap_CS_fsm_state62");
    sc_trace(mVcdFile, ap_CS_fsm_state63, "ap_CS_fsm_state63");
    sc_trace(mVcdFile, ap_CS_fsm_state108, "ap_CS_fsm_state108");
    sc_trace(mVcdFile, ap_CS_fsm_state109, "ap_CS_fsm_state109");
    sc_trace(mVcdFile, ap_CS_fsm_state110, "ap_CS_fsm_state110");
    sc_trace(mVcdFile, ap_CS_fsm_state111, "ap_CS_fsm_state111");
    sc_trace(mVcdFile, grp_fu_181_opcode, "grp_fu_181_opcode");
    sc_trace(mVcdFile, ap_return_0_preg, "ap_return_0_preg");
    sc_trace(mVcdFile, ap_return_1_preg, "ap_return_1_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

monte_carlo_both_pri::~monte_carlo_both_pri() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_gaussian_box_muller_fu_126;
    delete grp_custom_exp_double_s_fu_132;
    delete dut_dadddsub_64nsbkb_U22;
    delete dut_dadddsub_64nsbkb_U23;
    delete dut_dmul_64ns_64ndEe_U24;
    delete dut_dmul_64ns_64ndEe_U25;
    delete dut_ddiv_64ns_64neOg_U26;
    delete dut_ddiv_64ns_64neOg_U27;
    delete dut_dcmp_64ns_64nfYi_U28;
    delete dut_dcmp_64ns_64nfYi_U29;
}

void monte_carlo_both_pri::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void monte_carlo_both_pri::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv64_0;
}

void monte_carlo_both_pri::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv64_3FEE7078B0A726A6;
}

void monte_carlo_both_pri::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv64_416312D000000000;
}

void monte_carlo_both_pri::thread_ap_var_for_const4() {
    ap_var_for_const4 = ap_const_lv5_2;
}

void monte_carlo_both_pri::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_0_preg = ap_const_lv64_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state112.read())) {
            ap_return_0_preg = grp_fu_152_p2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_1_preg = ap_const_lv64_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state112.read())) {
            ap_return_1_preg = grp_fu_162_p2.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state76.read())) {
        call_payoff_sum_0_reg_56 = grp_fu_137_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        call_payoff_sum_0_reg_56 = ap_const_lv64_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_custom_exp_double_s_fu_132_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state58.read())) {
            grp_custom_exp_double_s_fu_132_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_custom_exp_double_s_fu_132_ap_ready.read())) {
            grp_custom_exp_double_s_fu_132_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_gaussian_box_muller_fu_126_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln184_fu_213_p2.read()))) {
            grp_gaussian_box_muller_fu_126_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_gaussian_box_muller_fu_126_ap_ready.read())) {
            grp_gaussian_box_muller_fu_126_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state53.read())) {
        guess_0_i_reg_91 = nextGuess_reg_103.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_gaussian_box_muller_fu_126_ap_done.read(), ap_const_logic_1))) {
        guess_0_i_reg_91 = ap_const_lv64_3FA47AE147AE147C;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state76.read())) {
        i_0_reg_80 = i_reg_430.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_80 = ap_const_lv24_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state53.read())) {
        nextGuess_reg_103 = grp_fu_152_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_gaussian_box_muller_fu_126_ap_done.read(), ap_const_logic_1))) {
        nextGuess_reg_103 = ap_const_lv64_3FE0A3D70A3D70A4;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        if (esl_seteq<1,1,1>(and_ln54_fu_261_p2.read(), ap_const_lv1_0)) {
            phi_ln54_reg_116 = reg_193.read();
        } else if (esl_seteq<1,1,1>(and_ln54_fu_261_p2.read(), ap_const_lv1_1)) {
            phi_ln54_reg_116 = bitcast_ln54_1_fu_273_p1.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state76.read())) {
        put_payoff_sum_0_reg_68 = grp_fu_145_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        put_payoff_sum_0_reg_68 = ap_const_lv64_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state69.read())) {
        a_assign_1_reg_471 = grp_fu_145_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(grp_gaussian_box_muller_fu_126_ap_done.read(), ap_const_logic_1))) {
        gauss_bm_reg_435 = grp_gaussian_box_muller_fu_126_ap_return.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_430 = i_fu_219_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        icmp_ln83_1_reg_453 = icmp_ln83_1_fu_301_p2.read();
        icmp_ln83_reg_448 = icmp_ln83_fu_295_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state69.read()))) {
        reg_193 = grp_fu_137_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state106.read()))) {
        reg_200 = grp_fu_167_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state58.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state64.read()))) {
        reg_206 = grp_fu_152_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state71.read())) {
        select_ln50_1_reg_483 = select_ln50_1_fu_408_p3.read();
        select_ln50_reg_478 = select_ln50_fu_359_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state106.read())) {
        tmp_1_reg_498 = grp_fu_173_p2.read();
    }
}

void monte_carlo_both_pri::thread_and_ln50_1_fu_402_p2() {
    and_ln50_1_fu_402_p2 = (or_ln50_1_fu_396_p2.read() & grp_fu_188_p2.read());
}

void monte_carlo_both_pri::thread_and_ln50_fu_353_p2() {
    and_ln50_fu_353_p2 = (or_ln50_fu_347_p2.read() & grp_fu_181_p2.read());
}

void monte_carlo_both_pri::thread_and_ln54_fu_261_p2() {
    and_ln54_fu_261_p2 = (or_ln54_fu_255_p2.read() & grp_fu_181_p2.read());
}

void monte_carlo_both_pri::thread_and_ln83_fu_311_p2() {
    and_ln83_fu_311_p2 = (or_ln83_fu_307_p2.read() & grp_fu_181_p2.read());
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state106() {
    ap_CS_fsm_state106 = ap_CS_fsm.read()[105];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state107() {
    ap_CS_fsm_state107 = ap_CS_fsm.read()[106];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state108() {
    ap_CS_fsm_state108 = ap_CS_fsm.read()[107];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state109() {
    ap_CS_fsm_state109 = ap_CS_fsm.read()[108];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state110() {
    ap_CS_fsm_state110 = ap_CS_fsm.read()[109];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state111() {
    ap_CS_fsm_state111 = ap_CS_fsm.read()[110];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state112() {
    ap_CS_fsm_state112 = ap_CS_fsm.read()[111];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state42() {
    ap_CS_fsm_state42 = ap_CS_fsm.read()[41];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state43() {
    ap_CS_fsm_state43 = ap_CS_fsm.read()[42];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state47() {
    ap_CS_fsm_state47 = ap_CS_fsm.read()[46];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state48() {
    ap_CS_fsm_state48 = ap_CS_fsm.read()[47];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state49() {
    ap_CS_fsm_state49 = ap_CS_fsm.read()[48];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state50() {
    ap_CS_fsm_state50 = ap_CS_fsm.read()[49];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state51() {
    ap_CS_fsm_state51 = ap_CS_fsm.read()[50];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state52() {
    ap_CS_fsm_state52 = ap_CS_fsm.read()[51];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state53() {
    ap_CS_fsm_state53 = ap_CS_fsm.read()[52];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state54() {
    ap_CS_fsm_state54 = ap_CS_fsm.read()[53];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state55() {
    ap_CS_fsm_state55 = ap_CS_fsm.read()[54];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state56() {
    ap_CS_fsm_state56 = ap_CS_fsm.read()[55];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state57() {
    ap_CS_fsm_state57 = ap_CS_fsm.read()[56];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state58() {
    ap_CS_fsm_state58 = ap_CS_fsm.read()[57];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state59() {
    ap_CS_fsm_state59 = ap_CS_fsm.read()[58];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state60() {
    ap_CS_fsm_state60 = ap_CS_fsm.read()[59];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state61() {
    ap_CS_fsm_state61 = ap_CS_fsm.read()[60];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state62() {
    ap_CS_fsm_state62 = ap_CS_fsm.read()[61];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state63() {
    ap_CS_fsm_state63 = ap_CS_fsm.read()[62];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state64() {
    ap_CS_fsm_state64 = ap_CS_fsm.read()[63];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state65() {
    ap_CS_fsm_state65 = ap_CS_fsm.read()[64];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state69() {
    ap_CS_fsm_state69 = ap_CS_fsm.read()[68];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state70() {
    ap_CS_fsm_state70 = ap_CS_fsm.read()[69];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state71() {
    ap_CS_fsm_state71 = ap_CS_fsm.read()[70];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state72() {
    ap_CS_fsm_state72 = ap_CS_fsm.read()[71];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state76() {
    ap_CS_fsm_state76 = ap_CS_fsm.read()[75];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void monte_carlo_both_pri::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void monte_carlo_both_pri::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state112.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void monte_carlo_both_pri::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void monte_carlo_both_pri::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state112.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void monte_carlo_both_pri::thread_ap_return_0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state112.read())) {
        ap_return_0 = grp_fu_152_p2.read();
    } else {
        ap_return_0 = ap_return_0_preg.read();
    }
}

void monte_carlo_both_pri::thread_ap_return_1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state112.read())) {
        ap_return_1 = grp_fu_162_p2.read();
    } else {
        ap_return_1 = ap_return_1_preg.read();
    }
}

void monte_carlo_both_pri::thread_bitcast_ln50_1_fu_367_p1() {
    bitcast_ln50_1_fu_367_p1 = a_assign_1_reg_471.read();
}

void monte_carlo_both_pri::thread_bitcast_ln50_fu_317_p1() {
    bitcast_ln50_fu_317_p1 = reg_193.read();
}

void monte_carlo_both_pri::thread_bitcast_ln54_1_fu_273_p1() {
    bitcast_ln54_1_fu_273_p1 = xor_ln54_fu_267_p2.read();
}

void monte_carlo_both_pri::thread_bitcast_ln54_fu_225_p1() {
    bitcast_ln54_fu_225_p1 = reg_193.read();
}

void monte_carlo_both_pri::thread_bitcast_ln83_fu_277_p1() {
    bitcast_ln83_fu_277_p1 = phi_ln54_reg_116.read();
}

void monte_carlo_both_pri::thread_grp_custom_exp_double_s_fu_132_ap_start() {
    grp_custom_exp_double_s_fu_132_ap_start = grp_custom_exp_double_s_fu_132_ap_start_reg.read();
}

void monte_carlo_both_pri::thread_grp_fu_137_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_137_opcode = ap_const_lv2_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state65.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state72.read()))) {
        grp_fu_137_opcode = ap_const_lv2_0;
    } else {
        grp_fu_137_opcode = "XX";
    }
}

void monte_carlo_both_pri::thread_grp_fu_137_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state72.read())) {
        grp_fu_137_p0 = call_payoff_sum_0_reg_56.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state65.read())) {
        grp_fu_137_p0 = reg_206.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_fu_137_p0 = nextGuess_reg_103.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_137_p0 = guess_0_i_reg_91.read();
    } else {
        grp_fu_137_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void monte_carlo_both_pri::thread_grp_fu_137_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state72.read())) {
        grp_fu_137_p1 = select_ln50_reg_478.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state65.read())) {
        grp_fu_137_p1 = ap_const_lv64_C059000000000000;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_fu_137_p1 = reg_200.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_137_p1 = nextGuess_reg_103.read();
    } else {
        grp_fu_137_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void monte_carlo_both_pri::thread_grp_fu_145_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state65.read())) {
        grp_fu_145_opcode = ap_const_lv2_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state72.read())) {
        grp_fu_145_opcode = ap_const_lv2_0;
    } else {
        grp_fu_145_opcode = "XX";
    }
}

void monte_carlo_both_pri::thread_grp_fu_145_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state72.read())) {
        grp_fu_145_p0 = put_payoff_sum_0_reg_68.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state65.read())) {
        grp_fu_145_p0 = ap_const_lv64_4059000000000000;
    } else {
        grp_fu_145_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void monte_carlo_both_pri::thread_grp_fu_145_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state72.read())) {
        grp_fu_145_p1 = select_ln50_1_reg_483.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state65.read())) {
        grp_fu_145_p1 = reg_206.read();
    } else {
        grp_fu_145_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void monte_carlo_both_pri::thread_grp_fu_152_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state58.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state64.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state53.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state59.read()) && 
          esl_seteq<1,1,1>(grp_custom_exp_double_s_fu_132_ap_done.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state48.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state107.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state112.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state54.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state55.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state56.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state57.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state49.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state50.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state52.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state60.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state61.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state62.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state63.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state108.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state109.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state110.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state111.read()))) {
        grp_fu_152_ce = ap_const_logic_1;
    } else {
        grp_fu_152_ce = ap_const_logic_0;
    }
}

void monte_carlo_both_pri::thread_grp_fu_152_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state107.read())) {
        grp_fu_152_p0 = reg_200.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state59.read())) {
        grp_fu_152_p0 = grp_custom_exp_double_s_fu_132_ap_return.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state48.read())) {
        grp_fu_152_p0 = reg_193.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        grp_fu_152_p0 = nextGuess_reg_103.read();
    } else {
        grp_fu_152_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void monte_carlo_both_pri::thread_grp_fu_152_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state107.read())) {
        grp_fu_152_p1 = ap_const_lv64_3FEE7078B0A726A6;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state59.read())) {
        grp_fu_152_p1 = ap_const_lv64_4059C2E8B55BA1C6;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state48.read())) {
        grp_fu_152_p1 = ap_const_lv64_3FE0000000000000;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        grp_fu_152_p1 = gauss_bm_reg_435.read();
    } else {
        grp_fu_152_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void monte_carlo_both_pri::thread_grp_fu_167_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        grp_fu_167_p0 = ap_const_lv64_3FA47AE147AE147C;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        grp_fu_167_p0 = call_payoff_sum_0_reg_56.read();
    } else {
        grp_fu_167_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void monte_carlo_both_pri::thread_grp_fu_167_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        grp_fu_167_p1 = nextGuess_reg_103.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        grp_fu_167_p1 = ap_const_lv64_416312D000000000;
    } else {
        grp_fu_167_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void monte_carlo_both_pri::thread_grp_fu_181_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state70.read())) {
        grp_fu_181_opcode = ap_const_lv5_2;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_181_opcode = ap_const_lv5_3;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        grp_fu_181_opcode = ap_const_lv5_4;
    } else {
        grp_fu_181_opcode =  (sc_lv<5>) ("XXXXX");
    }
}

void monte_carlo_both_pri::thread_grp_fu_181_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_181_p0 = phi_ln54_reg_116.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state70.read()))) {
        grp_fu_181_p0 = reg_193.read();
    } else {
        grp_fu_181_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void monte_carlo_both_pri::thread_grp_fu_181_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_181_p1 = ap_const_lv64_3F1A36E2EB1C432D;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state70.read()))) {
        grp_fu_181_p1 = ap_const_lv64_0;
    } else {
        grp_fu_181_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void monte_carlo_both_pri::thread_grp_gaussian_box_muller_fu_126_ap_start() {
    grp_gaussian_box_muller_fu_126_ap_start = grp_gaussian_box_muller_fu_126_ap_start_reg.read();
}

void monte_carlo_both_pri::thread_i_fu_219_p2() {
    i_fu_219_p2 = (!i_0_reg_80.read().is_01() || !ap_const_lv24_1.is_01())? sc_lv<24>(): (sc_biguint<24>(i_0_reg_80.read()) + sc_biguint<24>(ap_const_lv24_1));
}

void monte_carlo_both_pri::thread_icmp_ln184_fu_213_p2() {
    icmp_ln184_fu_213_p2 = (!i_0_reg_80.read().is_01() || !ap_const_lv24_989680.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_80.read() == ap_const_lv24_989680);
}

void monte_carlo_both_pri::thread_icmp_ln50_1_fu_341_p2() {
    icmp_ln50_1_fu_341_p2 = (!trunc_ln50_fu_331_p1.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln50_fu_331_p1.read() == ap_const_lv52_0);
}

void monte_carlo_both_pri::thread_icmp_ln50_2_fu_384_p2() {
    icmp_ln50_2_fu_384_p2 = (!tmp_6_fu_370_p4.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_6_fu_370_p4.read() != ap_const_lv11_7FF);
}

void monte_carlo_both_pri::thread_icmp_ln50_3_fu_390_p2() {
    icmp_ln50_3_fu_390_p2 = (!trunc_ln50_1_fu_380_p1.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln50_1_fu_380_p1.read() == ap_const_lv52_0);
}

void monte_carlo_both_pri::thread_icmp_ln50_fu_335_p2() {
    icmp_ln50_fu_335_p2 = (!tmp_s_fu_321_p4.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_s_fu_321_p4.read() != ap_const_lv11_7FF);
}

void monte_carlo_both_pri::thread_icmp_ln54_1_fu_249_p2() {
    icmp_ln54_1_fu_249_p2 = (!trunc_ln54_fu_239_p1.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln54_fu_239_p1.read() == ap_const_lv52_0);
}

void monte_carlo_both_pri::thread_icmp_ln54_fu_243_p2() {
    icmp_ln54_fu_243_p2 = (!tmp_fu_229_p4.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_229_p4.read() != ap_const_lv11_7FF);
}

void monte_carlo_both_pri::thread_icmp_ln83_1_fu_301_p2() {
    icmp_ln83_1_fu_301_p2 = (!trunc_ln83_fu_291_p1.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln83_fu_291_p1.read() == ap_const_lv52_0);
}

void monte_carlo_both_pri::thread_icmp_ln83_fu_295_p2() {
    icmp_ln83_fu_295_p2 = (!tmp_3_fu_281_p4.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_3_fu_281_p4.read() != ap_const_lv11_7FF);
}

void monte_carlo_both_pri::thread_or_ln50_1_fu_396_p2() {
    or_ln50_1_fu_396_p2 = (icmp_ln50_3_fu_390_p2.read() | icmp_ln50_2_fu_384_p2.read());
}

void monte_carlo_both_pri::thread_or_ln50_fu_347_p2() {
    or_ln50_fu_347_p2 = (icmp_ln50_1_fu_341_p2.read() | icmp_ln50_fu_335_p2.read());
}

void monte_carlo_both_pri::thread_or_ln54_fu_255_p2() {
    or_ln54_fu_255_p2 = (icmp_ln54_1_fu_249_p2.read() | icmp_ln54_fu_243_p2.read());
}

void monte_carlo_both_pri::thread_or_ln83_fu_307_p2() {
    or_ln83_fu_307_p2 = (icmp_ln83_1_reg_453.read() | icmp_ln83_reg_448.read());
}

void monte_carlo_both_pri::thread_select_ln50_1_fu_408_p3() {
    select_ln50_1_fu_408_p3 = (!and_ln50_1_fu_402_p2.read()[0].is_01())? sc_lv<64>(): ((and_ln50_1_fu_402_p2.read()[0].to_bool())? a_assign_1_reg_471.read(): ap_const_lv64_0);
}

void monte_carlo_both_pri::thread_select_ln50_fu_359_p3() {
    select_ln50_fu_359_p3 = (!and_ln50_fu_353_p2.read()[0].is_01())? sc_lv<64>(): ((and_ln50_fu_353_p2.read()[0].to_bool())? reg_193.read(): ap_const_lv64_0);
}

void monte_carlo_both_pri::thread_tmp_3_fu_281_p4() {
    tmp_3_fu_281_p4 = bitcast_ln83_fu_277_p1.read().range(62, 52);
}

void monte_carlo_both_pri::thread_tmp_6_fu_370_p4() {
    tmp_6_fu_370_p4 = bitcast_ln50_1_fu_367_p1.read().range(62, 52);
}

void monte_carlo_both_pri::thread_tmp_fu_229_p4() {
    tmp_fu_229_p4 = bitcast_ln54_fu_225_p1.read().range(62, 52);
}

void monte_carlo_both_pri::thread_tmp_s_fu_321_p4() {
    tmp_s_fu_321_p4 = bitcast_ln50_fu_317_p1.read().range(62, 52);
}

void monte_carlo_both_pri::thread_trunc_ln50_1_fu_380_p1() {
    trunc_ln50_1_fu_380_p1 = bitcast_ln50_1_fu_367_p1.read().range(52-1, 0);
}

void monte_carlo_both_pri::thread_trunc_ln50_fu_331_p1() {
    trunc_ln50_fu_331_p1 = bitcast_ln50_fu_317_p1.read().range(52-1, 0);
}

void monte_carlo_both_pri::thread_trunc_ln54_fu_239_p1() {
    trunc_ln54_fu_239_p1 = bitcast_ln54_fu_225_p1.read().range(52-1, 0);
}

void monte_carlo_both_pri::thread_trunc_ln83_fu_291_p1() {
    trunc_ln83_fu_291_p1 = bitcast_ln83_fu_277_p1.read().range(52-1, 0);
}

void monte_carlo_both_pri::thread_xor_ln54_fu_267_p2() {
    xor_ln54_fu_267_p2 = (bitcast_ln54_fu_225_p1.read() ^ ap_const_lv64_8000000000000000);
}

void monte_carlo_both_pri::thread_ap_NS_fsm() {
    if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state1))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_NS_fsm = ap_ST_fsm_state2;
        } else {
            ap_NS_fsm = ap_ST_fsm_state1;
        }
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state2))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln184_fu_213_p2.read()))) {
            ap_NS_fsm = ap_ST_fsm_state77;
        } else {
            ap_NS_fsm = ap_ST_fsm_state3;
        }
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state3))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(grp_gaussian_box_muller_fu_126_ap_done.read(), ap_const_logic_1))) {
            ap_NS_fsm = ap_ST_fsm_state4;
        } else {
            ap_NS_fsm = ap_ST_fsm_state3;
        }
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state4))
    {
        ap_NS_fsm = ap_ST_fsm_state5;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state5))
    {
        ap_NS_fsm = ap_ST_fsm_state6;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state6))
    {
        ap_NS_fsm = ap_ST_fsm_state7;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state7))
    {
        ap_NS_fsm = ap_ST_fsm_state8;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state8))
    {
        ap_NS_fsm = ap_ST_fsm_state9;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state9))
    {
        ap_NS_fsm = ap_ST_fsm_state10;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state10))
    {
        ap_NS_fsm = ap_ST_fsm_state11;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state11))
    {
        ap_NS_fsm = ap_ST_fsm_state12;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state12))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, and_ln83_fu_311_p2.read()))) {
            ap_NS_fsm = ap_ST_fsm_state54;
        } else {
            ap_NS_fsm = ap_ST_fsm_state13;
        }
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state13))
    {
        ap_NS_fsm = ap_ST_fsm_state14;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state14))
    {
        ap_NS_fsm = ap_ST_fsm_state15;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state15))
    {
        ap_NS_fsm = ap_ST_fsm_state16;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state16))
    {
        ap_NS_fsm = ap_ST_fsm_state17;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state17))
    {
        ap_NS_fsm = ap_ST_fsm_state18;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state18))
    {
        ap_NS_fsm = ap_ST_fsm_state19;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state19))
    {
        ap_NS_fsm = ap_ST_fsm_state20;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state20))
    {
        ap_NS_fsm = ap_ST_fsm_state21;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state21))
    {
        ap_NS_fsm = ap_ST_fsm_state22;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state22))
    {
        ap_NS_fsm = ap_ST_fsm_state23;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state23))
    {
        ap_NS_fsm = ap_ST_fsm_state24;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state24))
    {
        ap_NS_fsm = ap_ST_fsm_state25;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state25))
    {
        ap_NS_fsm = ap_ST_fsm_state26;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state26))
    {
        ap_NS_fsm = ap_ST_fsm_state27;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state27))
    {
        ap_NS_fsm = ap_ST_fsm_state28;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state28))
    {
        ap_NS_fsm = ap_ST_fsm_state29;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state29))
    {
        ap_NS_fsm = ap_ST_fsm_state30;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state30))
    {
        ap_NS_fsm = ap_ST_fsm_state31;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state31))
    {
        ap_NS_fsm = ap_ST_fsm_state32;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state32))
    {
        ap_NS_fsm = ap_ST_fsm_state33;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state33))
    {
        ap_NS_fsm = ap_ST_fsm_state34;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state34))
    {
        ap_NS_fsm = ap_ST_fsm_state35;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state35))
    {
        ap_NS_fsm = ap_ST_fsm_state36;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state36))
    {
        ap_NS_fsm = ap_ST_fsm_state37;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state37))
    {
        ap_NS_fsm = ap_ST_fsm_state38;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state38))
    {
        ap_NS_fsm = ap_ST_fsm_state39;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state39))
    {
        ap_NS_fsm = ap_ST_fsm_state40;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state40))
    {
        ap_NS_fsm = ap_ST_fsm_state41;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state41))
    {
        ap_NS_fsm = ap_ST_fsm_state42;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state42))
    {
        ap_NS_fsm = ap_ST_fsm_state43;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state43))
    {
        ap_NS_fsm = ap_ST_fsm_state44;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state44))
    {
        ap_NS_fsm = ap_ST_fsm_state45;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state45))
    {
        ap_NS_fsm = ap_ST_fsm_state46;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state46))
    {
        ap_NS_fsm = ap_ST_fsm_state47;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state47))
    {
        ap_NS_fsm = ap_ST_fsm_state48;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state48))
    {
        ap_NS_fsm = ap_ST_fsm_state49;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state49))
    {
        ap_NS_fsm = ap_ST_fsm_state50;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state50))
    {
        ap_NS_fsm = ap_ST_fsm_state51;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state51))
    {
        ap_NS_fsm = ap_ST_fsm_state52;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state52))
    {
        ap_NS_fsm = ap_ST_fsm_state53;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state53))
    {
        ap_NS_fsm = ap_ST_fsm_state4;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state54))
    {
        ap_NS_fsm = ap_ST_fsm_state55;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state55))
    {
        ap_NS_fsm = ap_ST_fsm_state56;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state56))
    {
        ap_NS_fsm = ap_ST_fsm_state57;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state57))
    {
        ap_NS_fsm = ap_ST_fsm_state58;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state58))
    {
        ap_NS_fsm = ap_ST_fsm_state59;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state59))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state59.read()) && esl_seteq<1,1,1>(grp_custom_exp_double_s_fu_132_ap_done.read(), ap_const_logic_1))) {
            ap_NS_fsm = ap_ST_fsm_state60;
        } else {
            ap_NS_fsm = ap_ST_fsm_state59;
        }
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state60))
    {
        ap_NS_fsm = ap_ST_fsm_state61;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state61))
    {
        ap_NS_fsm = ap_ST_fsm_state62;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state62))
    {
        ap_NS_fsm = ap_ST_fsm_state63;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state63))
    {
        ap_NS_fsm = ap_ST_fsm_state64;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state64))
    {
        ap_NS_fsm = ap_ST_fsm_state65;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state65))
    {
        ap_NS_fsm = ap_ST_fsm_state66;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state66))
    {
        ap_NS_fsm = ap_ST_fsm_state67;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state67))
    {
        ap_NS_fsm = ap_ST_fsm_state68;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state68))
    {
        ap_NS_fsm = ap_ST_fsm_state69;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state69))
    {
        ap_NS_fsm = ap_ST_fsm_state70;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state70))
    {
        ap_NS_fsm = ap_ST_fsm_state71;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state71))
    {
        ap_NS_fsm = ap_ST_fsm_state72;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state72))
    {
        ap_NS_fsm = ap_ST_fsm_state73;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state73))
    {
        ap_NS_fsm = ap_ST_fsm_state74;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state74))
    {
        ap_NS_fsm = ap_ST_fsm_state75;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state75))
    {
        ap_NS_fsm = ap_ST_fsm_state76;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state76))
    {
        ap_NS_fsm = ap_ST_fsm_state2;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state77))
    {
        ap_NS_fsm = ap_ST_fsm_state78;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state78))
    {
        ap_NS_fsm = ap_ST_fsm_state79;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state79))
    {
        ap_NS_fsm = ap_ST_fsm_state80;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state80))
    {
        ap_NS_fsm = ap_ST_fsm_state81;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state81))
    {
        ap_NS_fsm = ap_ST_fsm_state82;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state82))
    {
        ap_NS_fsm = ap_ST_fsm_state83;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state83))
    {
        ap_NS_fsm = ap_ST_fsm_state84;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state84))
    {
        ap_NS_fsm = ap_ST_fsm_state85;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state85))
    {
        ap_NS_fsm = ap_ST_fsm_state86;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state86))
    {
        ap_NS_fsm = ap_ST_fsm_state87;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state87))
    {
        ap_NS_fsm = ap_ST_fsm_state88;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state88))
    {
        ap_NS_fsm = ap_ST_fsm_state89;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state89))
    {
        ap_NS_fsm = ap_ST_fsm_state90;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state90))
    {
        ap_NS_fsm = ap_ST_fsm_state91;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state91))
    {
        ap_NS_fsm = ap_ST_fsm_state92;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state92))
    {
        ap_NS_fsm = ap_ST_fsm_state93;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state93))
    {
        ap_NS_fsm = ap_ST_fsm_state94;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state94))
    {
        ap_NS_fsm = ap_ST_fsm_state95;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state95))
    {
        ap_NS_fsm = ap_ST_fsm_state96;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state96))
    {
        ap_NS_fsm = ap_ST_fsm_state97;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state97))
    {
        ap_NS_fsm = ap_ST_fsm_state98;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state98))
    {
        ap_NS_fsm = ap_ST_fsm_state99;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state99))
    {
        ap_NS_fsm = ap_ST_fsm_state100;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state100))
    {
        ap_NS_fsm = ap_ST_fsm_state101;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state101))
    {
        ap_NS_fsm = ap_ST_fsm_state102;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state102))
    {
        ap_NS_fsm = ap_ST_fsm_state103;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state103))
    {
        ap_NS_fsm = ap_ST_fsm_state104;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state104))
    {
        ap_NS_fsm = ap_ST_fsm_state105;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state105))
    {
        ap_NS_fsm = ap_ST_fsm_state106;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state106))
    {
        ap_NS_fsm = ap_ST_fsm_state107;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state107))
    {
        ap_NS_fsm = ap_ST_fsm_state108;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state108))
    {
        ap_NS_fsm = ap_ST_fsm_state109;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state109))
    {
        ap_NS_fsm = ap_ST_fsm_state110;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state110))
    {
        ap_NS_fsm = ap_ST_fsm_state111;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state111))
    {
        ap_NS_fsm = ap_ST_fsm_state112;
    }
    else if (esl_seteq<1,112,112>(ap_CS_fsm.read(), ap_ST_fsm_state112))
    {
        ap_NS_fsm = ap_ST_fsm_state1;
    }
    else
    {
        ap_NS_fsm =  (sc_lv<112>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}
}

